config/routes.rb
Rails.application.routes.draw do

  root 'landing#index'
  resources :users, only: %i[create new]
  resources :contributions, only: %I[index new create]
  resources :groups, only: %I[index new create show]
  
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  get 'ungrouped', to: 'contributions#ungrouped'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :contribution_groups
  has_many :groups, through: :contribution_groups

  validates :name, presence: true, length: { minimum: 3, maximun: 30 }
  validates_numericality_of :amount, greater_than: 0, allow_nil: true

  scope :desc, -> { includes(:author).order('created_at DESC') }
end

app/models/contribution_group.rb
class ContributionGroup < ApplicationRecord
  belongs_to :contribution
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :contribution_groups
  has_many :contributions, through: :contribution_groups
  has_one_attached :image

  validates :name, presence: true, length: { minimum: 3, maximum: 30 }
  validates :image, presence: true

  scope :asc, -> { order('name ASC') }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :contributions, foreign_key: :author_id, dependent: :destroy
  has_many :groups, foreign_key: :author_id

  validates_uniqueness_of :username
  validates :username, presence: true, length: { minimum: 3, maximum: 30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:author_id]) if session[:author_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_user
    redirect_to new_user_path unless logged_in?
  end
end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  before_action :require_user

  def index
    return if current_user.contributions.size.zero?

    @contributions = if params[:image]
                       current_user.contributions.includes(:groups).desc
                     else
                       current_user.contributions.includes(:groups).desc.select do |contribution|
                         contribution.groups.exists?
                       end
                     end
  end

  def ungrouped
    return if current_user.contributions.size.zero?

    @contributions = current_user.contributions.includes(:groups).desc.reject do |contribution|
      contribution.groups.exists?
    end
  end

  def new
    @contribution = Contribution.new
    @groups = current_user.groups
  end

  def create
    @contribution = current_user.contributions.build(contribution_params)
    @group = Group.find_by(id: group_params[:group_id])
    @contribution.groups << @group unless @group.nil?

    if @contribution.save
      flash[:success] = 'Contribution Added!'
      redirect_to contributions_path
    else
      flash.now[:error] = @contribution.errors.full_messages
      render :new
    end
  end

  private

  def contribution_params
    params.require(:contribution).permit(:name, :amount)
  end

  def group_params
    params.require(:contribution).permit(:group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show]
  before_action :require_user

  def index
    @groups = current_user.groups.asc unless current_user.groups.size.zero?
  end

  def new
    @group = Group.new
  end

  def create
    @group = current_user.groups.build(group_params)
    if @group.save
      flash[:success] = "#{@group.name} Group created"
      redirect_to groups_path
    else
      flash.now[:error] = @group.errors.full_messages
      render :new
    end
  end

  def show
    if current_user.groups.include? @group
      @contributions = nil
      @contributions = @group.contributions.desc if @group.contributions.exists?
    else
      redirect_to groups_path
    end
  end

  private

  def set_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :image)
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  before_action :require_user

  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    @user = User.find_by(username: params[:session][:username])
    if @user
      session[:author_id] = @user.id
      flash[:success] = 'Successfully logged in.'
      redirect_to root_path
    else
      flash.now[:danger] = 'Error logging in.'
      render 'new'
    end
  end

  def destroy
    reset_session
    redirect_to login_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:author_id] = @user.id
      flash[:success] = "Welcome to Contri_B #{@user.username}"
      redirect_to root_path
    else
      flash.now[:error] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def app_nav(current_user)
    if logged_in?
      "<ul class = 'justify-content-end list-style-none col-md-8'>
          #{link_to current_user.username, '/#', class: 'nav-item  fa fa-user btn btn-primary mx-2 white'}
          #{link_to 'Contributions', contributions_path, class: 'nav-item btn btn-light mx-2 white'}
          #{link_to 'Ungrouped Contributions', ungrouped_path, class: 'nav-item btn btn-light mx-2 white'}
          #{link_to 'Contribution Groups', groups_path, class: 'nav-item btn btn-light mx-2 white'}
          #{link_to 'Log Out', '/logout', class: 'navbar-right nav-item btn btn-danger mx-2 text-decoration-none white'}

      </ul>".html_safe
    else
      "<ul class='d-flex justify-content-end list-style-none'>
        #{link_to 'Sign Up', new_user_path,
                  class: 'navbar-right nav-item btn btn-light mx-2 text-decoration-none white'}

        #{link_to 'Log In', '/login', class: 'navbar-right nav-item btn btn-light text-decoration-none white'}
      </ul>".html_safe
    end
  end

  def status(group)
    stat = group.contributions.sum(&:amount)
    if stat >= 100_000
      "<p class='font-weight-bold text-danger'>Rating: Expensive</p>".html_safe
    elsif stat >= 10_000
      "<p class='font-weight-bold text-success'>Rating: Medium</p>".html_safe
    else
      "<p class='font-weight-bold'>Rating: Cheap </p>".html_safe
    end
  end
end

app/helpers/contributions_helper.rb
module ContributionsHelper
  def show_contributions(name, contributions)
    render partial: name, locals: { obj: contributions } if contributions
  end

  def show_image(contribution)
    return unless contribution.groups.exists?

    "<div class='col-md-4'> #{image_tag(contribution.groups.first.image, class: 'group-img')}</div>".html_safe
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def show_groups(name, groups)
    render partial: name, locals: { obj: groups } if groups
  end

  def show_group_image(group)
    "<div class='col-sm-2'> #{image_tag(group.image, class: 'group-img')}</div>".html_safe if group.image.attached?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/contributions/_list.html.erb
<div class="container-fluid ">
<div class="row">
  <div class="col-sm-12 total">
    <span>Total amount:</span> 
    <span>&#36;<%= obj.sum{|contribution| contribution.amount} %></span>
  </div>
    


  <div class="container-fluid ">
    <div class="row row-cols-1 row-cols-md-3 g-4" > 

    <% obj.each do |contribution| %>
    <div class="col">
      <div class="card text-white bg-dark h-100">
        <div class="col-sm-12 col-md-6">
          <%= show_image(contribution)%>
          <div class="col-sm-7">
          <div class="card-body">
            <h3><%= contribution.name %></h3>
           
            <p class="card-text"> <%= number_to_currency(contribution.amount, precision: 0) %></p>
            <p class="card-text"><small class="text-muted"> Created on: <%= contribution.created_at.day %>-<%= contribution.created_at.month %>-<%= contribution.created_at.year %> </small></p>
          </div>
        </div>
      </div>
    </div>  
    </div>
      <% end %>
  </div>
</div>
</div>

app/views/contributions/index.html.erb
<% content_for(:title, "Contributions") %>

<%= show_contributions('list',@contributions)  %>

<div class=" row text-center btn-background">
    <%= link_to 'ADD CONTRIBUTION', new_contribution_path, class: "col-sm-12  button text-center" %>
</div>

app/views/contributions/new.html.erb
<% content_for(:title, "New contribution") %>

<h1 class="text-center">Create Contribution</h1>

<div class="sign_form bg-custom-light rounded  p-2 py-5">
    <% if @groups.nil?%>
        <%= link_to 'Create Group', new_group_path %>
    <% end %>
    <div class="row">
        <div class="col-xs-1 col-md-3"></div>
        <div class="col-xs-10 col-md-6 ">
            <%= form_with(model: @contribution, local: true) do |form| %>
                <div class="form-group">
                    <%= form.label :name %>
                    <%= form.text_field :name, placeholder: "Name", id: "name", class: "form-control" %>
                </div>
                <div class="form-group">
                    <%= form.label :amount %>
                    <%= form.number_field :amount, placeholder: "Price", id: "amount", class: "form-control" %><br>
                </div>
                <% unless @groups.nil? %>
                    <div class="form-group">
                        <%= form.select :group_id, options_from_collection_for_select(@groups, :id, :name), {:include_blank => 'Choose a group'}, {class: "form-control"} %>
                    </div>
                <% end %>
                <%= submit_tag("ADD NEW CONTRIBUTION", :class=>"btn btn-success button") %>
            <% end %>
        </div>
        <div class="col-xs-1 col-md-3 "></div>
    </div>
</div>

app/views/contributions/ungrouped.html.erb
<% content_for(:title, "Ungrouped Contributions") %>

<%= show_contributions('list',@contributions)  %>

<div class=" row text-center btn-background">
    <%= link_to 'ADD CONTRIBUTION', new_contribution_path, class: "col-sm-12  button text-center" %>
</div>

app/views/groups/_list.html.erb
<div class="row mb-5">
    <% obj.each do |group| %>
      <%= link_to(group) do %>
        <div class="col-sm-12 col-md-6">
          <div class="row transcation-listing">
                    <%= show_group_image(group)%>

            <div class="col-sm-7 grey-color">
            <p class="text-secondary h6 m-0 p-0 py-1"><strong>Group Name: </strong><%= group.name %></p>
            <%= status(group) %>
            <p class="text-secondary h6 m-0 p-0 py-2"><strong>Created: </strong> <%= group.created_at.day %>-<%= group.created_at.month %>-<%= group.created_at.year %></p>
            </div>
          </div>
        </div>
      <% end %>
    <% end %>
</div>

app/views/groups/index.html.erb
<% content_for(:title, "Groups") %>
<%= show_groups('list',@groups)  %>

<div class="  row text-center btn-background">
    <%= link_to 'ADD GROUP', new_group_path, class: "col-sm-12 button text-center "%>
</div>

app/views/groups/new.html.erb
<% content_for(:title, "New Group") %>

<h1 class="text-center">Create Contribution Group</h1>

<div class="row">
    <div class="col-xs-1 col-md-3"></div>
    <div class="col-xs-10 col-md-6 ">
        <%= form_with(model: @group, local: true) do |f| %>
            <div class="form-group">
                <%= f.label :name %>
                <%= f.text_field :name, autofocus: true, placeholder: "Group Name", class: "form-control" %>
            </div>
            <div class="form-group">
                <%= f.label :image %>
                <%= f.file_field :image, class: "form-control" %>
            </div>
           <%= submit_tag("Create Group", :class=>"btn btn-success button") %>
        <% end %>
    </div>
    <div class="col-xs-1 col-md-3 "></div>
</div>


            

app/views/groups/show.html.erb
<% content_for(:title, "All Groups") %>


<% @group.contributions.each do |contribution| %>
    <div class="col">
      <div class="card text-white bg-dark h-100">
        <div class="col-md-5">
          <%= show_image(contribution)%>
          <div class="col-md-7">
          <div class="card-body">
            <h3>Title: <%= contribution.name %></h3>
            <p class= 'card-title'> Author: <%= contribution.author.username %></p>
            <p class="card-text">Amount: <%= contribution.amount %></p>
          
            <p class="card-text"><small class="text-muted">Created on: <%= contribution.created_at.day %>-<%= contribution.created_at.month %>-<%= contribution.created_at.year %> </small></p>
          </div>
        </div>
      </div>
    </div>  
    </div>
      <% end %>
  </div>
</div>
</div>


<div class=" row text-center btn-background">
    <%= link_to 'ADD CONTRIBUTION', new_contribution_path, class: "col-sm-12  button text-center" %>
</div>

app/views/landing/index.html.erb
 <h1>Hello <%= @current_user.username %></h1>
 <p> Welcome To Contri_B. </p>
 <p> Create Contribution groups in which you can keep track of how much and what items you are contributing to. </p>
 <p> Enjoy!</p>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top blue-background white">
  <%= link_to "CONTRI_B", root_path, class: "navbar-brand white " %>
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <div class="navbar-collapse collapse navbar-responsive-collapse">

      <%= app_nav(current_user) %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Contributions" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <%= render 'layouts/nav' %>
    
    <div class="container">
      <%= bootstrap_flash %>
      <%= yield %>
    </div>

  </body>
</html>

app/views/users/new.html.erb
<h1 class="text-center">Sign up</h1>

<div class="row">
    
    <div class="col-xs-1 col-md-3"></div>
    <div class="col-xs-10 col-md-6 ">
    
        <%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

            <div class="form-group">
                <%= f.label :username %>
                <%= f.text_field :username, autofocus: true, autocomplete: "username", placeholder: "Enter your username", class: "form-control" %>
            </div>
            <%= f.submit "Sign up", class: 'btn btn-success' %>

        <% end %>

    </div>
    <div class="col-xs-1 col-md-3 "></div>

</div>